### ISSUE TITLE
Dead links (error 404)

### ISSUE THREAD

**Issue by patchworquill** [Project-Northern-Lights/capacity-backend#4]
### Wrong paths

**example:** helpAPI//v0/appEtdSsNPk2GvjhA/Organizations%20in%20Need?pageSize=20&sort%5B0%5D%5Bfield%5D=City&sort%5B0%5D%5Bdirection%5D=asc&filterByFormula=AND():1 

### Result

https://projectnorthernlights.ca/requests

_says_

"An error has occurred"

**Comment by JoshMLiu** [comment]
@patchworquill I think this issue is for another repo. Connect_backend maybe?
